server:
  port: 8087

spring:
  application:
    name: Automatic Photography Formatter
  messages:
    basename: messages/messages, messages/error, messages/apfMessages
    cache-duration: -1
    encoding: UTF-8